from . import fsm_stage
from . import fsm_tag
from . import fsm_team
from . import fsm_location
from . import fsm_checklist
from . import fsm_worksheet
from . import fsm_equipment
from . import fsm_installation
from . import fsm_maintenance
from . import fsm_timesheet
from . import fsm_material
from . import fsm_template
from . import fsm_order
from . import project_project
from . import res_config_settings
from . import crm_lead
from . import sale_order
from . import account_move
from . import stock_picking
from . import res_partner
from . import product_template
from . import hr_employee
from . import res_users
