{
    'name': 'Aasha Field Service',
    'version': '19.0.1.2.0',
    'category': 'Services/Field Service',
    'summary': 'Work orders, SLA, checklists, materials, timesheets, sign-off and billing',
    'description': """
Aasha Field Service
===================
Dispatch-style field service for Community and Enterprise.

Work orders (Draft → Planned → In Progress → Done), teams, locations,
SLA, preventive maintenance, checklists, worksheets, customer sign-off,
materials with stock, timesheets, quotations and invoices.

Integrates with CRM, Sales, Project, Inventory, Employees, Calendar,
Contacts and Accounting without replacing core models.
    """,
    'author': 'Aasha Lubes',
    'license': 'LGPL-3',
    'depends': [
        'base_setup',
        'mail',
        'calendar',
        'contacts',
        'hr',
        'hr_hourly_cost',
        'hr_timesheet',
        'project',
        'product',
        'sale_management',
        'stock',
        'account',
        'crm',
        'portal',
        'rating',
        'analytic',
    ],
    'data': [
        'security/fsm_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/fsm_stage_data.xml',
        'data/fsm_cron_data.xml',
        'data/mail_template_data.xml',
        'wizard/fsm_sign_report_views.xml',
        'wizard/fsm_create_invoice_views.xml',
        'report/fsm_service_report.xml',
        'report/fsm_worksheet_report.xml',
        'report/fsm_invoice_report.xml',
        'views/fsm_stage_views.xml',
        'views/fsm_tag_views.xml',
        'views/fsm_team_views.xml',
        'views/fsm_location_views.xml',
        'views/fsm_checklist_views.xml',
        'views/fsm_worksheet_views.xml',
        'views/fsm_template_views.xml',
        'views/fsm_equipment_views.xml',
        'views/fsm_installation_views.xml',
        'views/fsm_maintenance_views.xml',
        'views/fsm_order_views.xml',
        'views/fsm_timesheet_views.xml',
        'views/fsm_material_views.xml',
        'views/project_views.xml',
        'views/crm_lead_views.xml',
        'views/sale_order_views.xml',
        'views/res_partner_views.xml',
        'views/hr_employee_views.xml',
        'views/res_config_settings_views.xml',
        'views/mail_activity_plan_views.xml',
        'views/product_views.xml',
        'views/res_users_views.xml',
        'views/fsm_menus.xml',
        'views/fsm_portal_templates.xml',
    ],
    'demo': [
        'data/fsm_demo.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'al_field_service/static/src/scss/fsm.scss',
            'al_field_service/static/src/js/fsm_gantt.js',
            'al_field_service/static/src/js/fsm_map.js',
            'al_field_service/static/src/xml/fsm_gantt.xml',
            'al_field_service/static/src/xml/fsm_map.xml',
        ],
        'web.assets_frontend': [
            'al_field_service/static/src/scss/fsm_portal.scss',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
